import { useEffect, useState } from 'react'
import { api } from '../api'
import type { Assessment, Material } from '../types'
import { Badge, Button, Card, ErrorNotice, InfoNotice, Loading, PageHeader, statusTone, number } from '../components/ui'
import { Icon } from '../components/icons'

export function AssessmentPage({ materialId, onNext }: { materialId?: number; onNext: (id: number) => void }) {
  const [materials,setMaterials]=useState<Material[]>([]); const [selected,setSelected]=useState(materialId || 0); const [assessment,setAssessment]=useState<Assessment|null>(null); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(() => { void (async () => { try { const rows = await api.materials(); setMaterials(rows); setSelected(current => current || rows[0]?.id || 0) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load materials') } finally { setLoading(false) } })() }, [])
  useEffect(()=>{ if(selected) api.assessment(selected).then(setAssessment).catch(()=>setAssessment(null)) },[selected])
  const run=async()=>{ if(!selected)return; setBusy(true);setError(''); try{setAssessment(await api.runAssessment(selected))}catch(e){setError(e instanceof Error?e.message:'Assessment failed')}finally{setBusy(false)} }
  if(loading) return <Loading label="Loading assessment workspace…" />
  const material=materials.find(x=>x.id===selected)
  return <><PageHeader eyebrow="DECISION ENGINE" title="AI circularity assessment" description="Reloop decides the most suitable next life before it searches for a partner." actions={material && <Button onClick={()=>onNext(material.id)} variant="secondary" disabled={!assessment}>Find partners</Button>} />{error&&<ErrorNotice message={error}/>}<Card className="assessment-selector"><div className="selector-row"><label className="field"><span>Select surplus material</span><select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{materials.map(m=><option key={m.id} value={m.id}>{m.name} · {number(m.remaining_quantity)} {m.unit} · {m.condition}</option>)}</select></label><Button onClick={run} disabled={!selected||busy} icon="brain">{busy?'Assessing…':'Run AI assessment'}</Button></div></Card>{!assessment?<Card><InfoNotice>Run the assessment to see a transparent score for Reuse, Refurbish, Recycle and Recover.</InfoNotice></Card>:<div className="assessment-layout"><Card className="score-hero"><div className="score-ring"><strong>{Math.round(assessment.condition_score)}</strong><span>condition</span></div><div><div className="eyebrow">RECOMMENDED NEXT LIFE</div><h2>{assessment.recommendation}</h2><p>Confidence {Math.round(assessment.confidence*100)}%</p><Badge tone={statusTone(assessment.recommendation)}>{assessment.recommendation}</Badge></div></Card><Card title="Pathway scores"><div className="score-list">{Object.entries(assessment.scores).sort((a,b)=>b[1]-a[1]).map(([name,score])=><div className="score-row" key={name}><div className="score-label"><strong>{name}</strong><span>{Math.round(score)}%</span></div><div className="bar"><span style={{width:`${Math.max(0,Math.min(100,score))}%`}} /></div></div>)}</div></Card><Card title="Why this pathway?"><div className="reason-list">{assessment.reasons.map((r,i)=><div key={i}><span className="check-bullet"><Icon name="check" size={15}/></span><span>{r}</span></div>)}</div><div className="factor-grid">{Object.entries(assessment.factor_breakdown).map(([k,v])=><div key={k}><small>{k}</small><strong>{Math.round(v)}%</strong></div>)}</div></Card><Card title="Methodology"><p className="prose">{assessment.methodology}</p></Card></div>}</>
}
