import { useCallback, useEffect, useState } from 'react'
import { api } from '../api'
import type { Driver } from '../types'
import { Badge, Button, Card, EmptyState, ErrorNotice, Field, Loading, PageHeader, statusTone } from '../components/ui'
import { Icon } from '../components/icons'

export function DriversPage() {
  const [drivers,setDrivers]=useState<Driver[]>([]);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [form,setForm]=useState({name:'New driver',email:'driver3@reloop.demo',password:'demo12345',phone:'',vehicle_type:'EV VAN',vehicle_number:'MH-04-RL-3003'})
  const load=useCallback(() => api.drivers().then(setDrivers).catch(e=>setError(e instanceof Error?e.message:'Unable to load driver directory')), [])
  useEffect(() => { void load() }, [load])
  const set=(k:keyof typeof form)=>(v:string)=>setForm(p=>({...p,[k]:v}))
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api.createDriver(form);setShow(false);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to create driver')}finally{setBusy(false)}}
  return <><PageHeader eyebrow="FLEET OPERATIONS" title="Drivers & vehicles" description="Logistics partners control driver assignment. Drivers receive jobs, publish GPS and mark verified arrival; they cannot self-assign arbitrary transfers." actions={<Button icon="plus" onClick={()=>setShow(v=>!v)}>Add driver</Button>}/>{error&&<ErrorNotice message={error} onRetry={load}/>} {show&&<Card title="Register driver"><form onSubmit={submit} className="form-grid compact"><Field label="Driver name" value={form.name} onChange={set('name')} required/><Field label="Login email" value={form.email} onChange={set('email')} type="email" required/><Field label="Initial password" value={form.password} onChange={set('password')} type="password" required/><Field label="Phone" value={form.phone} onChange={set('phone')}/><Field label="Vehicle type" value={form.vehicle_type} onChange={set('vehicle_type')} options={['BIKE','EV VAN','MINI TRUCK','TRUCK']}/><Field label="Vehicle number" value={form.vehicle_number} onChange={set('vehicle_number')} required/><div className="full-span form-actions"><Button variant="secondary" onClick={()=>setShow(false)}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Creating…':'Create driver'}</Button></div></form></Card>}<Card title="Active driver directory">{drivers.length===0?<EmptyState icon="users" title="No active drivers" message="Register your first driver to make transport assignment operational."/>:<div className="driver-grid">{drivers.map(d=><div className="driver-directory-card" key={d.id}><div className="driver-avatar large">{d.name.slice(0,1)}</div><div className="driver-info"><div className="driver-name"><strong>{d.name}</strong><Badge tone={statusTone(d.status)}>{d.status}</Badge></div><span>{d.driver_code}</span><span>{d.vehicle_type} · {d.vehicle_number}</span><span>{d.phone||'No phone'}</span></div><div className="driver-state"><Icon name={d.status==='AVAILABLE'?'check':'activity'} size={17}/><small>{d.status==='AVAILABLE'?'Ready for assignment':d.status.replace(/_/g,' ')}</small></div></div>)}</div>}</Card></>
}
