import { useEffect, useState } from 'react'
import { api } from '../api'
import type { Impact } from '../types'
import { Badge, Card, ErrorNotice, Loading, PageHeader, StatCard, number, currency } from '../components/ui'
import { Icon } from '../components/icons'

export function ImpactPage() {
  const [data,setData]=useState<Impact|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);api.impact().then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load impact')).finally(()=>setLoading(false))};useEffect(() => { void load() }, [])
  if(loading)return <Loading label="Loading verified impact ledger…"/>
  return <><PageHeader eyebrow="MEASURE" title="Verified circular impact" description="Only reviewer-verified outcome evidence contributes to this ledger. Transport arrival and physical receipt alone never create circular impact."/>{error&&<ErrorNotice message={error} onRetry={load}/>}<div className="stats-grid"><StatCard label="Value recovered" value={currency(data?.value_recovered||0)} icon="activity" tone="teal"/><StatCard label="Waste avoided" value={`${number(data?.waste_avoided_kg||0)} kg`} icon="layers" tone="violet"/><StatCard label="CO₂ avoided" value={`${number(data?.co2_avoided_kg||0)} kg`} icon="route" tone="navy"/><StatCard label="Verified exchanges" value={data?.verified_transfers||0} icon="shield" tone="amber"/></div><div className="two-col"><Card title="Verified pathways"><div className="pathway-impact">{Object.entries(data?.by_pathway||{}).length===0?<div className="muted">No verified outcomes yet.</div>:Object.entries(data!.by_pathway).map(([k,v])=><div className="impact-row" key={k}><div><strong>{k}</strong><span>{data!.pathway_counts[k]||0} verified exchange{(data!.pathway_counts[k]||0)===1?'':'s'}</span></div><strong>{number(v)} units</strong></div>)}</div></Card><Card title="Trust indicators"><div className="trust-grid"><div><Icon name="shield" size={22}/><strong>{data?.verified_quantity||0}</strong><span>verified units</span></div><div><Icon name="users" size={22}/><strong>{Math.round(data?.average_match_score||0)}%</strong><span>avg match score</span></div><div><Icon name="check" size={22}/><strong>100%</strong><span>impact from verified evidence</span></div></div><Badge tone="green">Evidence-backed ledger</Badge></Card></div><Card className="impact-callout"><div><div className="eyebrow">WHY THIS MATTERS</div><h2>Reloop separates logistics proof from circular proof.</h2><p>Delivery says the material arrived. Outcome evidence says what happened to it. Platform verification decides what is counted.</p></div><Icon name="shield" size={42}/></Card></>
}
