import { useEffect, useState } from 'react'
import { api } from '../api'
import type { Match, Material, Need, Organization } from '../types'
import { Badge, Button, Card, EmptyState, ErrorNotice, InfoNotice, Loading, PageHeader, number, statusTone } from '../components/ui'
import { Icon } from '../components/icons'

export function MatchingPage({ materialId, onTransport }: { materialId?: number; onTransport?: (match: Match) => void }) {
  const [materials,setMaterials]=useState<Material[]>([]); const [selected,setSelected]=useState(materialId||0); const [matches,setMatches]=useState<Match[]>([]); const [needs,setNeeds]=useState<Need[]>([]); const [partners,setPartners]=useState<Organization[]>([]); const [busy,setBusy]=useState<number|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const load=async(id:number)=>{setSelected(id);setError(''); try{const [m,n,p]=await Promise.all([api.matches(id),api.needs().catch(()=>[]),api.organizations('RECEIVER')]);setMatches(m);setNeeds(n);setPartners(p.filter(x=>x.id!==m[0]?.source?.id))}catch(e){setError(e instanceof Error?e.message:'Unable to build partner matches')} }
  useEffect(() => { void (async () => { try { const [m, n] = await Promise.all([api.materials(), api.needs().catch(() => [])]); setMaterials(m); setNeeds(n); const id = materialId || m[0]?.id; if (id) await load(id) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load matching workspace') } finally { setLoading(false) } })() }, [materialId])
  const send=async(match:Match)=>{if(!match.partner?.id)return;setBusy(match.id||0);setError('');try{const result=await api.requestMatch({material_id:match.material_id,partner_organization_id:match.partner.id,need_id:match.need_id});setMatches(rows=>rows.map(x=>x.id===match.id?result:x))}catch(e){setError(e instanceof Error?e.message:'Could not send request')}finally{setBusy(null)}}
  if(loading)return <Loading label="Building multi-factor partner matches…"/>
  const material=materials.find(m=>m.id===selected)
  const openNeeds=needs.filter(n=>n.remaining_quantity>0)
  return <><PageHeader eyebrow="SMART MATCH" title="Find the right circular partner" description="Matching considers material, condition, quantity, partner need/capability, location and time."/>{error&&<ErrorNotice message={error}/>}<Card className="selector-card"><div className="selector-row"><label className="field"><span>Surplus material</span><select value={selected} onChange={e=>load(Number(e.target.value))}>{materials.map(m=><option key={m.id} value={m.id}>{m.name} · {number(m.remaining_quantity)} {m.unit}</option>)}</select></label><div className="selection-facts">{material&&<><Badge tone={statusTone(material.condition)}>{material.condition}</Badge><span>{material.category}</span><span>{material.city}</span></>}</div></div></Card>{openNeeds.length===0&&<InfoNotice>No active receiver needs are currently available. Receivers can create a need to improve the matching signal.</InfoNotice>}<div className="match-grid">{matches.length===0?<EmptyState icon="users" title="No suitable partners yet" message="Run the AI assessment first or create a receiver need for the material category."/>:matches.map(match=><Card key={`${match.id}-${match.partner.id}`} className="match-card"><div className="match-score"><strong>{Math.round(match.match_score)}%</strong><span>match</span></div><div className="match-main"><div className="match-title"><div><h3>{match.partner.name}</h3><span>{match.partner.organization_type} · {match.partner.city}</span></div><Badge tone={statusTone(match.status)}>{match.status}</Badge></div><div className="factor-inline">{Object.entries(match.factor_breakdown).slice(0,4).map(([k,v])=><span key={k}><b>{Math.round(v)}%</b> {k}</span>)}</div><ul className="reason-mini">{match.reasons.slice(0,3).map((r,i)=><li key={i}><Icon name="check" size={14}/>{r}</li>)}</ul><div className="match-footer"><span><Icon name="location" size={15}/>{match.distance_km.toFixed(1)} km away</span>{match.status==='ACCEPTED'?<Button variant="success" icon="truck" onClick={()=>onTransport?.(match)}>Arrange transport</Button>:match.status==='REQUESTED'?<Badge tone="amber">Awaiting partner</Badge>:<Button disabled={busy===match.id} onClick={()=>send(match)} icon="send">{busy===match.id?'Sending…':'Send request'}</Button>}</div></div></Card>)}</div></>
}
