import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Button, Card, EmptyState, ErrorNotice, Loading, PageHeader, Badge, statusTone, currency, number, Field, InfoNotice } from '../components/ui'
import { Icon } from '../components/icons'
import type { Material, Role } from '../types'

export function MaterialsPage({ role, onOpenAssessment, onOpenMatching }: { role: Role; onOpenAssessment: (id: number) => void; onOpenMatching: (id: number) => void }) {
  const [items, setItems] = useState<Material[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState('')
  const load = () => { setLoading(true); const fn = role === 'ORGANIZATION' ? api.materials : api.marketplace; fn().then(setItems).catch(e => setError(e instanceof Error ? e.message : 'Unable to load materials')).finally(() => setLoading(false)) }
  useEffect(() => { void load() }, [role])
  const filtered = useMemo(() => items.filter(x => `${x.name} ${x.category} ${x.city}`.toLowerCase().includes(query.toLowerCase())), [items, query])
  const title = role === 'ORGANIZATION' ? 'My surplus inventory' : role === 'RECYCLER' ? 'Recovery opportunities' : 'Available materials'
  const desc = role === 'ORGANIZATION' ? 'Manage what your organization can put back into the circular network.' : role === 'RECYCLER' ? 'Review materials that may be suitable for recycling or recovery.' : 'Browse surplus materials that fit your current needs.'
  if (loading) return <Loading label="Loading material network…" />
  return <>
    <PageHeader eyebrow="MATERIAL NETWORK" title={title} description={desc} actions={<Button variant="secondary" icon="refresh" onClick={load}>Refresh</Button>} />
    {error && <ErrorNotice message={error} onRetry={load} />}
    <div className="toolbar"><label className="search-field"><Icon name="search" size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search material, category or city" /></label><span className="toolbar-count">{filtered.length} records</span></div>
    {filtered.length === 0 ? <EmptyState icon="search" title="No matching materials" message="Try a different search or add a new surplus listing." /> : <div className="material-grid">{filtered.map(item => <Card key={item.id} className="material-card"><div className="material-top"><Badge tone={statusTone(item.status)}>{item.status.replace(/_/g, ' ')}</Badge><span>#{String(item.id).padStart(5,'0')}</span></div><div className="material-title"><h3>{item.name}</h3><span>{item.category}</span></div><p>{item.description}</p><div className="material-specs"><div><small>Remaining</small><strong>{number(item.remaining_quantity)} {item.unit}</strong></div><div><small>Condition</small><strong>{item.condition}</strong></div><div><small>Value</small><strong>{currency(item.estimated_value)}</strong></div></div><div className="material-footer"><span><Icon name="location" size={15} />{item.city}</span>{role === 'ORGANIZATION' ? <div className="button-row"><Button variant="secondary" onClick={() => onOpenAssessment(item.id)} icon="brain">AI assessment</Button><Button onClick={() => onOpenMatching(item.id)} icon="users">Find partners</Button></div> : <Badge tone="blue">Marketplace</Badge>}</div></Card>)}</div>}
  </>
}

export function AddMaterialPage({ onDone, onCancel }: { onDone: (id: number) => void; onCancel?: () => void }) {
  const [form, setForm] = useState({ name:'Office furniture', category:'furniture', description:'', quantity:'10', unit:'units', condition:'GOOD', age_years:'1', city:'Navi Mumbai', state:'Maharashtra', latitude:'19.082', longitude:'73.0175', estimated_value:'0' }); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [photo,setPhoto]=useState<File|null>(null)
  const set = (key: string) => (value: string) => setForm(prev => ({ ...prev, [key]: value }))
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const created = await api.createMaterial({...form, quantity:Number(form.quantity), age_years:Number(form.age_years), latitude:Number(form.latitude), longitude:Number(form.longitude), estimated_value:Number(form.estimated_value), category:form.category.toLowerCase() }); if(photo) await api.uploadMaterialImage(created.id,photo); onDone(created.id) } catch(err){ setError(err instanceof Error ? err.message : 'Unable to create material') } finally { setBusy(false) } }
  return <><PageHeader eyebrow="CREATE" title="Add surplus material" description="Capture the minimum operational data Reloop needs for AI assessment and partner matching."/><Card className="form-card"><form onSubmit={submit} className="form-grid">{error && <div className="full-span"><ErrorNotice message={error} /></div>}<Field label="Material name" value={form.name} onChange={set('name')} required placeholder="e.g. Office Chairs"/><Field label="Category" value={form.category} onChange={set('category')} required placeholder="furniture, electronics, paper…"/><Field label="Quantity" value={form.quantity} onChange={set('quantity')} type="number" min="0.01" step="0.01" required/><Field label="Unit" value={form.unit} onChange={set('unit')} options={['units','kg','tonnes','litres','pieces']}/><Field label="Condition" value={form.condition} onChange={set('condition')} options={['EXCELLENT','GOOD','FAIR','POOR']}/><Field label="Age (years)" value={form.age_years} onChange={set('age_years')} type="number" min="0" step="0.1"/><Field label="Estimated value (₹)" value={form.estimated_value} onChange={set('estimated_value')} type="number" min="0" step="1"/><Field label="City" value={form.city} onChange={set('city')} required/><Field label="State" value={form.state} onChange={set('state')} required/><Field label="Latitude" value={form.latitude} onChange={set('latitude')} type="number" step="0.000001" required/><Field label="Longitude" value={form.longitude} onChange={set('longitude')} type="number" step="0.000001" required/><label className="field full-span"><span>Description</span><textarea value={form.description} onChange={e => setForm(p=>({...p,description:e.target.value}))} rows={4} placeholder="What is the material, where did it come from, and what is its current condition?" /></label><label className="upload-drop full-span"><Icon name="camera" size={22}/><span><strong>Optional material photo</strong><small>{photo ? photo.name : 'Upload a clear photo for future vision-based assessment.'}</small></span><input type="file" accept="image/*" onChange={e => setPhoto(e.target.files?.[0] || null)} /></label><div className="full-span form-actions"><Button variant="secondary" onClick={() => onCancel?.()}>Cancel</Button><Button type="submit" disabled={busy} icon="check">{busy ? 'Creating…' : 'Create surplus listing'}</Button></div></form></Card><InfoNotice>After creation, run the AI assessment. The decision engine is explainable and is kept separate from partner matching.</InfoNotice></>
}
