import { useEffect, useState } from 'react'
import { api } from '../api'
import type { Need } from '../types'
import { Badge, Button, Card, EmptyState, ErrorNotice, Field, Loading, PageHeader, number, shortDate, statusTone } from '../components/ui'

export function NeedsPage() {
  const [needs,setNeeds]=useState<Need[]>([]);const [form,setForm]=useState({material_name:'Office Chairs',category:'furniture',quantity:'20',unit:'units',acceptable_condition:'GOOD',needed_by:'',notes:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const load=()=>api.needs().then(setNeeds).catch(e=>setError(e instanceof Error?e.message:'Unable to load needs'))
  useEffect(() => { void load() }, [])
  const set=(k:keyof typeof form)=>(v:string)=>setForm(p=>({...p,[k]:v}))
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api.createNeed({...form,quantity:Number(form.quantity),needed_by:form.needed_by?new Date(form.needed_by).toISOString():null});setForm(p=>({...p,quantity:'20',needed_by:'',notes:''}));await load()}catch(err){setError(err instanceof Error?err.message:'Unable to create need')}finally{setBusy(false)}}
  return <><PageHeader eyebrow="DEMAND SIGNAL" title="My material needs" description="Receiver demand helps organizations make higher-confidence partner decisions."/><div className="two-col"><Card title="Create a need"><form onSubmit={submit} className="form-grid compact">{error&&<div className="full-span"><ErrorNotice message={error}/></div>}<Field label="Material" value={form.material_name} onChange={set('material_name')} required/><Field label="Category" value={form.category} onChange={set('category')} required/><Field label="Quantity" value={form.quantity} onChange={set('quantity')} type="number" min="0.01" step="0.01" required/><Field label="Unit" value={form.unit} onChange={set('unit')} options={['units','kg','tonnes','pieces']}/><Field label="Acceptable condition" value={form.acceptable_condition} onChange={set('acceptable_condition')} options={['EXCELLENT','GOOD','FAIR','POOR']}/><Field label="Needed by" value={form.needed_by} onChange={set('needed_by')} type="date"/><label className="field full-span"><span>Notes</span><textarea value={form.notes} onChange={e=>setForm(p=>({...p,notes:e.target.value}))} rows={4} placeholder="Intended use, delivery preference, quality constraints…"/></label><div className="full-span form-actions"><Button type="submit" disabled={busy}>{busy?'Saving…':'Create material need'}</Button></div></form></Card><Card title="Open demand"><div className="need-list">{needs.length===0?<EmptyState title="No needs created" message="Add your first demand signal so the matching engine can find suitable material."/>:needs.map(n=><div className="need-item" key={n.id}><div><strong>{n.material_name}</strong><span>{n.category} · {number(n.remaining_quantity)} {n.unit} remaining</span></div><div className="need-right"><Badge tone={statusTone(n.status)}>{n.status}</Badge><small>{n.needed_by?shortDate(n.needed_by):'Flexible date'}</small></div></div>)}</div></Card></div></>
}
