import { useCallback, useEffect, useState } from 'react'
import { api } from '../api'
import type { Match, Role } from '../types'
import { Badge, Button, Card, EmptyState, ErrorNotice, Loading, PageHeader, statusTone, number } from '../components/ui'
import { Icon } from '../components/icons'

export function RequestsPage({ role, onArrange, onTrack }: { role: Role; onArrange: (match: Match) => void; onTrack: (transferId?: number) => void }) {
  const [rows,setRows]=useState<Match[]>([]); const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async()=>{setError('');try{setRows(role==='ORGANIZATION'?await api.sentMatches():await api.incomingMatches())}catch(e){setError(e instanceof Error?e.message:'Unable to load requests')}finally{setLoading(false)}},[role])
  useEffect(()=>{load();const timer=window.setInterval(load,3000);return()=>window.clearInterval(timer)},[load])
  const decide=async(id:number,decision:'ACCEPTED'|'REJECTED')=>{try{await api.decideMatch(id,decision);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update request')}}
  if(loading) return <Loading label="Loading live requests…"/>
  const org=role==='ORGANIZATION'
  return <><PageHeader eyebrow="REQUEST MANAGEMENT" title={org?'Requests sent':'Incoming requests'} description={org?'Track partner responses and move accepted matches into transport planning.':'Review offers addressed to your organization. Accepted requests remain pending transport until the source arranges dispatch.'} actions={<Button variant="secondary" icon="refresh" onClick={load}>Refresh</Button>}/>{error&&<ErrorNotice message={error} onRetry={load}/>}<Card>{rows.length===0?<EmptyState icon="send" title={org?'No partner requests yet':'No incoming requests'} message={org?'Run Smart Match for a material and send your first partner request.':'New organization offers will appear here automatically when a matching request is sent.'}/>:<div className="request-list">{rows.map(row=><div className="request-item" key={row.id || `${row.material_id}-${row.partner.id}`}><div className="request-icon"><Icon name={org?'send':'box'} size={21}/></div><div className="request-main"><div className="request-title"><div><strong>{org?row.partner.name:row.source?.name || 'Organization'}</strong><span>{org?row.partner.organization_type:row.source?.organization_type || '—'} · {org?row.partner.city:row.source?.city || '—'}</span></div><Badge tone={statusTone(row.status)}>{row.status}</Badge></div><div className="request-meta"><span>Material #{row.material_id}</span><span>{Math.round(row.match_score)}% match</span><span>{row.distance_km.toFixed(1)} km</span>{row.need_id&&<span>Need #{row.need_id}</span>}</div><div className="request-reasons">{row.reasons.slice(0,2).map((r,i)=><span key={i}><Icon name="check" size={13}/>{r}</span>)}</div></div><div className="request-actions">{org&&row.status==='ACCEPTED'&&row.id&&<Button icon="truck" onClick={()=>onArrange(row)}>Arrange transport</Button>}{!org&&row.status==='REQUESTED'&&row.id&&<><Button variant="secondary" icon="x" onClick={()=>decide(row.id!,'REJECTED')}>Reject</Button><Button icon="check" onClick={()=>decide(row.id!,'ACCEPTED')}>Accept</Button></>}{!org&&row.status==='ACCEPTED'&&<Badge tone="green">Accepted · waiting for transport</Badge>}</div></div>)}</div>}</Card><Card className="process-card"><div className="process-line">{['Request','Accept','Transport','Track','Receive','Verify'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></div>)}</div></Card></>
}
